//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class ActiveUser : XPLiteObject
    {
        int fActiveUserID;
        [Key(true)]
        public int ActiveUserID
        {
            get { return fActiveUserID; }
            set { SetPropertyValue<int>(nameof(ActiveUserID), ref fActiveUserID, value); }
        }
        Users fUserID;
        [Association(@"ActiveUserReferencesUsers")]
        public Users UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<Users>(nameof(UserID), ref fUserID, value); }
        }
        DateTime fLoginDate;
        public DateTime LoginDate
        {
            get { return fLoginDate; }
            set { SetPropertyValue<DateTime>(nameof(LoginDate), ref fLoginDate, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        DateTime fLastRequestTS;
        public DateTime LastRequestTS
        {
            get { return fLastRequestTS; }
            set { SetPropertyValue<DateTime>(nameof(LastRequestTS), ref fLastRequestTS, value); }
        }
        int fRequestCount;
        public int RequestCount
        {
            get { return fRequestCount; }
            set { SetPropertyValue<int>(nameof(RequestCount), ref fRequestCount, value); }
        }
        string fNotes;
        [Size(150)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>(nameof(ts), ref fts, value); }
        }
        int fSessionExpireMin;
        public int SessionExpireMin
        {
            get { return fSessionExpireMin; }
            set { SetPropertyValue<int>(nameof(SessionExpireMin), ref fSessionExpireMin, value); }
        }
        [Association(@"UserActivityReferencesActiveUser")]
        public XPCollection<UserActivity> UserActivities { get { return GetCollection<UserActivity>(nameof(UserActivities)); } }
    }

}
