//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class ContactPerson : XPLiteObject
    {
        int fContactPersonID;
        [Key(true)]
        public int ContactPersonID
        {
            get { return fContactPersonID; }
            set { SetPropertyValue<int>(nameof(ContactPersonID), ref fContactPersonID, value); }
        }
        Client fClientID;
        [Association(@"ContactPersonReferencesClient")]
        public Client ClientID
        {
            get { return fClientID; }
            set { SetPropertyValue<Client>(nameof(ClientID), ref fClientID, value); }
        }
        string fName;
        [Size(150)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fPhone;
        [Size(50)]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fMobilePhone;
        [Size(50)]
        public string MobilePhone
        {
            get { return fMobilePhone; }
            set { SetPropertyValue<string>(nameof(MobilePhone), ref fMobilePhone, value); }
        }
        string fEmail;
        [Size(60)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fFAX;
        [Size(50)]
        public string FAX
        {
            get { return fFAX; }
            set { SetPropertyValue<string>(nameof(FAX), ref fFAX, value); }
        }
        string fNotes;
        [Size(200)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
    }

}
