//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class DayTransaction : XPLiteObject
    {
        int fDayTransactionID;
        [Key(true)]
        public int DayTransactionID
        {
            get { return fDayTransactionID; }
            set { SetPropertyValue<int>(nameof(DayTransactionID), ref fDayTransactionID, value); }
        }
        DateTime fCurrentDay;
        public DateTime CurrentDay
        {
            get { return fCurrentDay; }
            set { SetPropertyValue<DateTime>(nameof(CurrentDay), ref fCurrentDay, value); }
        }
        string fCurrentDayStr;
        [Size(250)]
        public string CurrentDayStr
        {
            get { return fCurrentDayStr; }
            set { SetPropertyValue<string>(nameof(CurrentDayStr), ref fCurrentDayStr, value); }
        }
        string fIzLokacije;
        [Size(250)]
        public string IzLokacije
        {
            get { return fIzLokacije; }
            set { SetPropertyValue<string>(nameof(IzLokacije), ref fIzLokacije, value); }
        }
        string fNaLokacijo;
        [Size(250)]
        public string NaLokacijo
        {
            get { return fNaLokacijo; }
            set { SetPropertyValue<string>(nameof(NaLokacijo), ref fNaLokacijo, value); }
        }
        int fProductID;
        public int ProductID
        {
            get { return fProductID; }
            set { SetPropertyValue<int>(nameof(ProductID), ref fProductID, value); }
        }
        string fProduct;
        [Size(250)]
        public string Product
        {
            get { return fProduct; }
            set { SetPropertyValue<string>(nameof(Product), ref fProduct, value); }
        }
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        decimal fQuantityKG;
        public decimal QuantityKG
        {
            get { return fQuantityKG; }
            set { SetPropertyValue<decimal>(nameof(QuantityKG), ref fQuantityKG, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
        int fRowCnt;
        public int RowCnt
        {
            get { return fRowCnt; }
            set { SetPropertyValue<int>(nameof(RowCnt), ref fRowCnt, value); }
        }
    }

}
