//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class DeliveryNoteItem : XPLiteObject
    {
        int fDeliveryNoteItemID;
        [Key(true)]
        public int DeliveryNoteItemID
        {
            get { return fDeliveryNoteItemID; }
            set { SetPropertyValue<int>(nameof(DeliveryNoteItemID), ref fDeliveryNoteItemID, value); }
        }
        DeliveryNote fDeliveryNoteID;
        [Association(@"DeliveryNoteItemReferencesDeliveryNote")]
        public DeliveryNote DeliveryNoteID
        {
            get { return fDeliveryNoteID; }
            set { SetPropertyValue<DeliveryNote>(nameof(DeliveryNoteID), ref fDeliveryNoteID, value); }
        }
        MeasuringUnit fMeasuringUnitID;
        [Association(@"DeliveryNoteItemReferencesMeasuringUnit")]
        public MeasuringUnit MeasuringUnitID
        {
            get { return fMeasuringUnitID; }
            set { SetPropertyValue<MeasuringUnit>(nameof(MeasuringUnitID), ref fMeasuringUnitID, value); }
        }
        string fPSN;
        [Size(50)]
        public string PSN
        {
            get { return fPSN; }
            set { SetPropertyValue<string>(nameof(PSN), ref fPSN, value); }
        }
        string fSID;
        [Size(50)]
        public string SID
        {
            get { return fSID; }
            set { SetPropertyValue<string>(nameof(SID), ref fSID, value); }
        }
        string fSupplierProductCode;
        [Size(25)]
        public string SupplierProductCode
        {
            get { return fSupplierProductCode; }
            set { SetPropertyValue<string>(nameof(SupplierProductCode), ref fSupplierProductCode, value); }
        }
        string fSupplierProductName;
        [Size(200)]
        public string SupplierProductName
        {
            get { return fSupplierProductName; }
            set { SetPropertyValue<string>(nameof(SupplierProductName), ref fSupplierProductName, value); }
        }
        decimal fLength;
        public decimal Length
        {
            get { return fLength; }
            set { SetPropertyValue<decimal>(nameof(Length), ref fLength, value); }
        }
        string fNEW;
        [Size(50)]
        public string NEW
        {
            get { return fNEW; }
            set { SetPropertyValue<string>(nameof(NEW), ref fNEW, value); }
        }
        int fItemQuantity;
        public int ItemQuantity
        {
            get { return fItemQuantity; }
            set { SetPropertyValue<int>(nameof(ItemQuantity), ref fItemQuantity, value); }
        }
        int fCountOfTradeUnits;
        public int CountOfTradeUnits
        {
            get { return fCountOfTradeUnits; }
            set { SetPropertyValue<int>(nameof(CountOfTradeUnits), ref fCountOfTradeUnits, value); }
        }
        string fPackagingLevel;
        [Size(15)]
        public string PackagingLevel
        {
            get { return fPackagingLevel; }
            set { SetPropertyValue<string>(nameof(PackagingLevel), ref fPackagingLevel, value); }
        }
        DateTime fProductionDate;
        public DateTime ProductionDate
        {
            get { return fProductionDate; }
            set { SetPropertyValue<DateTime>(nameof(ProductionDate), ref fProductionDate, value); }
        }
        int fProductItemCount;
        public int ProductItemCount
        {
            get { return fProductItemCount; }
            set { SetPropertyValue<int>(nameof(ProductItemCount), ref fProductItemCount, value); }
        }
        Product fProductID;
        [Association(@"DeliveryNoteItemReferencesProduct")]
        public Product ProductID
        {
            get { return fProductID; }
            set { SetPropertyValue<Product>(nameof(ProductID), ref fProductID, value); }
        }
        string fNotes;
        [Size(250)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
        [Association(@"InventoryDeliveriesReferencesDeliveryNoteItem")]
        public XPCollection<InventoryDeliveries> InventoryDeliveriesCollection { get { return GetCollection<InventoryDeliveries>(nameof(InventoryDeliveriesCollection)); } }
    }

}
