//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class DeliveryNote : XPLiteObject
    {
        int fDeliveryNoteID;
        [Key(true)]
        public int DeliveryNoteID
        {
            get { return fDeliveryNoteID; }
            set { SetPropertyValue<int>(nameof(DeliveryNoteID), ref fDeliveryNoteID, value); }
        }
        string fDeliveryNoteNumber;
        [Size(20)]
        public string DeliveryNoteNumber
        {
            get { return fDeliveryNoteNumber; }
            set { SetPropertyValue<string>(nameof(DeliveryNoteNumber), ref fDeliveryNoteNumber, value); }
        }
        Client fSupplierID;
        public Client SupplierID
        {
            get { return fSupplierID; }
            set { SetPropertyValue<Client>(nameof(SupplierID), ref fSupplierID, value); }
        }
        Location fLocationID;
        public Location LocationID
        {
            get { return fLocationID; }
            set { SetPropertyValue<Location>(nameof(LocationID), ref fLocationID, value); }
        }
        string fXMLFilePath;
        [Size(300)]
        public string XMLFilePath
        {
            get { return fXMLFilePath; }
            set { SetPropertyValue<string>(nameof(XMLFilePath), ref fXMLFilePath, value); }
        }
        DateTime fDeliveryNoteDate;
        public DateTime DeliveryNoteDate
        {
            get { return fDeliveryNoteDate; }
            set { SetPropertyValue<DateTime>(nameof(DeliveryNoteDate), ref fDeliveryNoteDate, value); }
        }
        string fNotes;
        [Size(500)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
        DeliveryNoteStatus fDeliveryNoteStatusID;
        public DeliveryNoteStatus DeliveryNoteStatusID
        {
            get { return fDeliveryNoteStatusID; }
            set { SetPropertyValue<DeliveryNoteStatus>(nameof(DeliveryNoteStatusID), ref fDeliveryNoteStatusID, value); }
        }
        string fProcessError;
        [Size(5000)]
        public string ProcessError
        {
            get { return fProcessError; }
            set { SetPropertyValue<string>(nameof(ProcessError), ref fProcessError, value); }
        }
        DateTime fRecivedMaterialDate;
        public DateTime RecivedMaterialDate
        {
            get { return fRecivedMaterialDate; }
            set { SetPropertyValue<DateTime>(nameof(RecivedMaterialDate), ref fRecivedMaterialDate, value); }
        }
        [Association(@"DeliveryNoteItemReferencesDeliveryNote")]
        public XPCollection<DeliveryNoteItem> DeliveryNoteItems { get { return GetCollection<DeliveryNoteItem>(nameof(DeliveryNoteItems)); } }
    }

}
