//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class Employee : XPLiteObject
    {
        int fEmployeeID;
        [Key(true)]
        public int EmployeeID
        {
            get { return fEmployeeID; }
            set { SetPropertyValue<int>(nameof(EmployeeID), ref fEmployeeID, value); }
        }
        string fFirstname;
        [Size(70)]
        public string Firstname
        {
            get { return fFirstname; }
            set { SetPropertyValue<string>(nameof(Firstname), ref fFirstname, value); }
        }
        string fLastname;
        [Size(80)]
        public string Lastname
        {
            get { return fLastname; }
            set { SetPropertyValue<string>(nameof(Lastname), ref fLastname, value); }
        }
        DateTime fBirthDate;
        public DateTime BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime>(nameof(BirthDate), ref fBirthDate, value); }
        }
        string fAddress;
        [Size(50)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fPost;
        [Size(50)]
        public string Post
        {
            get { return fPost; }
            set { SetPropertyValue<string>(nameof(Post), ref fPost, value); }
        }
        string fPostcode;
        [Size(15)]
        public string Postcode
        {
            get { return fPostcode; }
            set { SetPropertyValue<string>(nameof(Postcode), ref fPostcode, value); }
        }
        string fPhone;
        [Size(30)]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fEmail;
        [Size(50)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fPicture;
        [Size(150)]
        public string Picture
        {
            get { return fPicture; }
            set { SetPropertyValue<string>(nameof(Picture), ref fPicture, value); }
        }
        string fNotes;
        [Size(500)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
        [Association(@"UsersReferencesEmployee")]
        public XPCollection<Users> UsersCollection { get { return GetCollection<Users>(nameof(UsersCollection)); } }
    }

}
