//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class InventoryStock : XPLiteObject
    {
        int fInventoryStockID;
        [Key(true)]
        public int InventoryStockID
        {
            get { return fInventoryStockID; }
            set { SetPropertyValue<int>(nameof(InventoryStockID), ref fInventoryStockID, value); }
        }
        Product fProductID;
        [Association(@"InventoryStockReferencesProduct")]
        public Product ProductID
        {
            get { return fProductID; }
            set { SetPropertyValue<Product>(nameof(ProductID), ref fProductID, value); }
        }
        Location fLocationID;
        [Association(@"InventoryStockReferencesLocation")]
        public Location LocationID
        {
            get { return fLocationID; }
            set { SetPropertyValue<Location>(nameof(LocationID), ref fLocationID, value); }
        }
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        string fNotes;
        [Size(500)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
        decimal fQuantityPcs;
        public decimal QuantityPcs
        {
            get { return fQuantityPcs; }
            set { SetPropertyValue<decimal>(nameof(QuantityPcs), ref fQuantityPcs, value); }
        }
        [Association(@"InventoryDeliveriesReferencesInventoryStock")]
        public XPCollection<InventoryDeliveries> InventoryDeliveriesCollection { get { return GetCollection<InventoryDeliveries>(nameof(InventoryDeliveriesCollection)); } }
    }

}
