//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class IssueDocument : XPLiteObject
    {
        int fIssueDocumentID;
        [Key(true)]
        public int IssueDocumentID
        {
            get { return fIssueDocumentID; }
            set { SetPropertyValue<int>(nameof(IssueDocumentID), ref fIssueDocumentID, value); }
        }
        string fIssueNumber;
        [Size(20)]
        public string IssueNumber
        {
            get { return fIssueNumber; }
            set { SetPropertyValue<string>(nameof(IssueNumber), ref fIssueNumber, value); }
        }
        Client fBuyerID;
        [Association(@"IssueDocumentReferencesClient")]
        public Client BuyerID
        {
            get { return fBuyerID; }
            set { SetPropertyValue<Client>(nameof(BuyerID), ref fBuyerID, value); }
        }
        DateTime fIssueDate;
        public DateTime IssueDate
        {
            get { return fIssueDate; }
            set { SetPropertyValue<DateTime>(nameof(IssueDate), ref fIssueDate, value); }
        }
        string fName;
        [Size(300)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fNotes;
        [Size(2000)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        string fInternalDocument;
        [Size(50)]
        public string InternalDocument
        {
            get { return fInternalDocument; }
            set { SetPropertyValue<string>(nameof(InternalDocument), ref fInternalDocument, value); }
        }
        string fInvoiceNumber;
        [Size(50)]
        public string InvoiceNumber
        {
            get { return fInvoiceNumber; }
            set { SetPropertyValue<string>(nameof(InvoiceNumber), ref fInvoiceNumber, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
        IssueDocumentStatus fIssueStatus;
        [Association(@"IssueDocumentReferencesIssueDocumentStatus")]
        public IssueDocumentStatus IssueStatus
        {
            get { return fIssueStatus; }
            set { SetPropertyValue<IssueDocumentStatus>(nameof(IssueStatus), ref fIssueStatus, value); }
        }
        string fPermissionDoc;
        [Size(50)]
        public string PermissionDoc
        {
            get { return fPermissionDoc; }
            set { SetPropertyValue<string>(nameof(PermissionDoc), ref fPermissionDoc, value); }
        }
        [Association(@"IssueDocumentPositionReferencesIssueDocument")]
        public XPCollection<IssueDocumentPosition> IssueDocumentPositions { get { return GetCollection<IssueDocumentPosition>(nameof(IssueDocumentPositions)); } }
    }

}
