//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class Location : XPLiteObject
    {
        int fLocationID;
        [Key(true)]
        public int LocationID
        {
            get { return fLocationID; }
            set { SetPropertyValue<int>(nameof(LocationID), ref fLocationID, value); }
        }
        string fName;
        [Size(150)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        bool fIsBuyer;
        public bool IsBuyer
        {
            get { return fIsBuyer; }
            set { SetPropertyValue<bool>(nameof(IsBuyer), ref fIsBuyer, value); }
        }
        string fNotes;
        [Size(300)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
        bool fIsWarehouse;
        public bool IsWarehouse
        {
            get { return fIsWarehouse; }
            set { SetPropertyValue<bool>(nameof(IsWarehouse), ref fIsWarehouse, value); }
        }
        [Association(@"DeliveryNoteReferencesLocation")]
        public XPCollection<DeliveryNote> DeliveryNotes { get { return GetCollection<DeliveryNote>(nameof(DeliveryNotes)); } }
        [Association(@"InventoryStockReferencesLocation")]
        public XPCollection<InventoryStock> InventoryStocks { get { return GetCollection<InventoryStock>(nameof(InventoryStocks)); } }
        [Association(@"InventoryDeliveriesReferencesLocation")]
        public XPCollection<InventoryDeliveries> InventoryDeliveriesCollection { get { return GetCollection<InventoryDeliveries>(nameof(InventoryDeliveriesCollection)); } }
        [Association(@"InventoryDeliveriesLocationReferencesLocation")]
        public XPCollection<InventoryDeliveriesLocation> InventoryDeliveriesLocations { get { return GetCollection<InventoryDeliveriesLocation>(nameof(InventoryDeliveriesLocations)); } }
        [Association(@"InventoryDeliveriesLocationReferencesLocation1")]
        public XPCollection<InventoryDeliveriesLocation> InventoryDeliveriesLocations1 { get { return GetCollection<InventoryDeliveriesLocation>(nameof(InventoryDeliveriesLocations1)); } }
    }

}
