//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class MobileTransaction : XPLiteObject
    {
        int fMobileTransactionID;
        [Key(true)]
        public int MobileTransactionID
        {
            get { return fMobileTransactionID; }
            set { SetPropertyValue<int>(nameof(MobileTransactionID), ref fMobileTransactionID, value); }
        }
        InventoryDeliveriesLocation fInventoryDeliveriesLocationID;
        [Association(@"MobileTransactionReferencesInventoryDeliveriesLocation")]
        public InventoryDeliveriesLocation InventoryDeliveriesLocationID
        {
            get { return fInventoryDeliveriesLocationID; }
            set { SetPropertyValue<InventoryDeliveriesLocation>(nameof(InventoryDeliveriesLocationID), ref fInventoryDeliveriesLocationID, value); }
        }
        string fScannedProductCode;
        [Size(500)]
        public string ScannedProductCode
        {
            get { return fScannedProductCode; }
            set { SetPropertyValue<string>(nameof(ScannedProductCode), ref fScannedProductCode, value); }
        }
        string fNotes;
        [Size(300)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
        string fUIDCode;
        [Size(250)]
        public string UIDCode
        {
            get { return fUIDCode; }
            set { SetPropertyValue<string>(nameof(UIDCode), ref fUIDCode, value); }
        }
        Client fSupplierID;
        [Association(@"MobileTransactionReferencesClient")]
        public Client SupplierID
        {
            get { return fSupplierID; }
            set { SetPropertyValue<Client>(nameof(SupplierID), ref fSupplierID, value); }
        }
        Product fProductID;
        [Association(@"MobileTransactionReferencesProduct")]
        public Product ProductID
        {
            get { return fProductID; }
            set { SetPropertyValue<Product>(nameof(ProductID), ref fProductID, value); }
        }
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        MeasuringUnit fUnitOfMeasureID;
        [Association(@"MobileTransactionReferencesMeasuringUnit")]
        public MeasuringUnit UnitOfMeasureID
        {
            get { return fUnitOfMeasureID; }
            set { SetPropertyValue<MeasuringUnit>(nameof(UnitOfMeasureID), ref fUnitOfMeasureID, value); }
        }
        [Association(@"IssueDocumentPositionReferencesMobileTransaction")]
        public XPCollection<IssueDocumentPosition> IssueDocumentPositions { get { return GetCollection<IssueDocumentPosition>(nameof(IssueDocumentPositions)); } }
    }

}
