//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class Settings : XPLiteObject
    {
        int fSettingsID;
        [Key(true)]
        public int SettingsID
        {
            get { return fSettingsID; }
            set { SetPropertyValue<int>(nameof(SettingsID), ref fSettingsID, value); }
        }
        int fIssueDocumentNumber;
        public int IssueDocumentNumber
        {
            get { return fIssueDocumentNumber; }
            set { SetPropertyValue<int>(nameof(IssueDocumentNumber), ref fIssueDocumentNumber, value); }
        }
    }

}
