//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class UserActivity : XPLiteObject
    {
        int fUserActivityID;
        [Key(true)]
        public int UserActivityID
        {
            get { return fUserActivityID; }
            set { SetPropertyValue<int>(nameof(UserActivityID), ref fUserActivityID, value); }
        }
        ActiveUser fActiveUserID;
        [Association(@"UserActivityReferencesActiveUser")]
        public ActiveUser ActiveUserID
        {
            get { return fActiveUserID; }
            set { SetPropertyValue<ActiveUser>(nameof(ActiveUserID), ref fActiveUserID, value); }
        }
        string fCode;
        [Size(15)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fNotes;
        [Size(150)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime fts;
        public DateTime ts
        {
            get { return fts; }
            set { SetPropertyValue<DateTime>(nameof(ts), ref fts, value); }
        }
    }

}
