//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ETT_DAL.ETTPotocnik
{

    public partial class Users : XPLiteObject
    {
        int fUserID;
        [Key(true)]
        public int UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<int>(nameof(UserID), ref fUserID, value); }
        }
        Role fRoleID;
        [Association(@"UsersReferencesRole")]
        public Role RoleID
        {
            get { return fRoleID; }
            set { SetPropertyValue<Role>(nameof(RoleID), ref fRoleID, value); }
        }
        string fUsername;
        [Size(30)]
        public string Username
        {
            get { return fUsername; }
            set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
        }
        string fPassword;
        [Size(30)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        Employee fEmployeeID;
        [Association(@"UsersReferencesEmployee")]
        public Employee EmployeeID
        {
            get { return fEmployeeID; }
            set { SetPropertyValue<Employee>(nameof(EmployeeID), ref fEmployeeID, value); }
        }
        bool fGrantAppAccess;
        public bool GrantAppAccess
        {
            get { return fGrantAppAccess; }
            set { SetPropertyValue<bool>(nameof(GrantAppAccess), ref fGrantAppAccess, value); }
        }
        string fNotes;
        [Size(150)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        DateTime ftsInsert;
        public DateTime tsInsert
        {
            get { return ftsInsert; }
            set { SetPropertyValue<DateTime>(nameof(tsInsert), ref ftsInsert, value); }
        }
        int ftsInsertUserID;
        public int tsInsertUserID
        {
            get { return ftsInsertUserID; }
            set { SetPropertyValue<int>(nameof(tsInsertUserID), ref ftsInsertUserID, value); }
        }
        DateTime ftsUpdate;
        public DateTime tsUpdate
        {
            get { return ftsUpdate; }
            set { SetPropertyValue<DateTime>(nameof(tsUpdate), ref ftsUpdate, value); }
        }
        int ftsUpdateUserID;
        public int tsUpdateUserID
        {
            get { return ftsUpdateUserID; }
            set { SetPropertyValue<int>(nameof(tsUpdateUserID), ref ftsUpdateUserID, value); }
        }
        [Association(@"ActiveUserReferencesUsers")]
        public XPCollection<ActiveUser> ActiveUsers { get { return GetCollection<ActiveUser>(nameof(ActiveUsers)); } }
        [Association(@"InventoryDeliveriesLocationReferencesUsers")]
        public XPCollection<InventoryDeliveriesLocation> InventoryDeliveriesLocations { get { return GetCollection<InventoryDeliveriesLocation>(nameof(InventoryDeliveriesLocations)); } }
    }

}
